---
- hosts: all
  vars: 
    provider:
      host: "{{ inventory_hostname }}"
      transport: "{{ transport }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - name: interface description
      ios_config:
        provider: "{{ provider }}"
        lines:
          - no description
        parents: "interface {{ inter }}"